"""Subscription plan definitions and Razorpay plan ID placeholders."""

PLANS = {
    "basic_monthly": {
        "code": "basic",
        "name": "Basic",
        "price_inr": 199,
        "billing_period": "monthly",
        "razorpay_plan_id": "plan_basic_monthly",
        "features": ["dashboard", "signals", "journal", "calculator"],
    },
    "basic_yearly": {
        "code": "basic",
        "name": "Basic",
        "price_inr": 1990,
        "billing_period": "yearly",
        "razorpay_plan_id": "plan_basic_yearly",
        "features": ["dashboard", "signals", "journal", "calculator"],
    },
    "pro_monthly": {
        "code": "pro",
        "name": "Pro",
        "price_inr": 499,
        "billing_period": "monthly",
        "razorpay_plan_id": "plan_pro_monthly",
        "features": [
            "dashboard",
            "signals",
            "journal",
            "journal_analytics",
            "calculator",
            "seller_mode",
            "multi_index",
            "alerts",
        ],
    },
    "pro_yearly": {
        "code": "pro",
        "name": "Pro",
        "price_inr": 4990,
        "billing_period": "yearly",
        "razorpay_plan_id": "plan_pro_yearly",
        "features": [
            "dashboard",
            "signals",
            "journal",
            "journal_analytics",
            "calculator",
            "seller_mode",
            "multi_index",
            "alerts",
        ],
    },
    "ultra_monthly": {
        "code": "ultra",
        "name": "Ultra",
        "price_inr": 999,
        "billing_period": "monthly",
        "razorpay_plan_id": "plan_ultra_monthly",
        "features": [
            "dashboard",
            "signals",
            "journal",
            "journal_analytics",
            "calculator",
            "seller_mode",
            "multi_index",
            "alerts",
            "upstox_api_exec",
            "backtester",
        ],
    },
    "ultra_yearly": {
        "code": "ultra",
        "name": "Ultra",
        "price_inr": 9990,
        "billing_period": "yearly",
        "razorpay_plan_id": "plan_ultra_yearly",
        "features": [
            "dashboard",
            "signals",
            "journal",
            "journal_analytics",
            "calculator",
            "seller_mode",
            "multi_index",
            "alerts",
            "upstox_api_exec",
            "backtester",
        ],
    },
    "pay_per_expiry": {
        "code": "basic",
        "name": "Pay Per Expiry",
        "price_inr": 49,
        "billing_period": "single",
        "razorpay_plan_id": None,
        "features": ["dashboard", "signals", "journal", "calculator"],
        "duration_hours": 24,
    },
    "lifetime": {
        "code": "lifetime",
        "name": "Lifetime",
        "price_inr": 9999,
        "billing_period": "one_time",
        "razorpay_plan_id": None,
        "features": [
            "dashboard",
            "signals",
            "journal",
            "journal_analytics",
            "calculator",
            "seller_mode",
            "multi_index",
            "alerts",
            "upstox_api_exec",
            "backtester",
        ],
    },
    "student_monthly": {
        "code": "basic",
        "name": "Student",
        "price_inr": 99,
        "billing_period": "monthly",
        "razorpay_plan_id": "plan_student_monthly",
        "features": ["dashboard", "signals", "journal", "calculator"],
    },
}

TIER_RANK = {"free": 0, "basic": 1, "pro": 2, "ultra": 3, "lifetime": 4}

FEATURE_MIN_TIER = {
    "dashboard": "basic",
    "signals": "basic",
    "journal": "basic",
    "journal_analytics": "basic",
    "calculator": "basic",
    "seller_mode": "pro",
    "multi_index": "pro",
    "alerts": "pro",
    "upstox_api_exec": "ultra",
    "backtester": "ultra",
}
